# Generated by Django 4.0.2 on 2022-07-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='condicao',
            field=models.CharField(choices=[('P', 'Professor'), ('A', 'Aluno')], max_length=1),
        ),
    ]
