# Generated by Django 4.0.2 on 2022-07-08 12:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_usuario_condicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=300)),
                ('nota', models.SmallIntegerField()),
                ('data_criacao', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Redacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('area', multiselectfield.db.fields.MultiSelectField(choices=[('CET', 'Ciencias Exatas e da Terra'), ('CB', 'Ciências Biológicas'), ('CSA', 'Ciências Sociais Aplicadas'), ('E', 'Engenharias'), ('LLA', 'Linguística, Letras e Artes'), ('CH', 'Ciências Humanas')], max_length=20)),
                ('tema', models.CharField(max_length=45)),
                ('data_criacao', models.DateTimeField(default=datetime.date.today)),
                ('conteudo', models.TextField(max_length=15000)),
                ('descricao', models.TextField(blank=True, default=None, max_length=300, null=True)),
                ('curtidas', models.SmallIntegerField(default=0)),
                ('compartilhamentos', models.SmallIntegerField(default=0)),
                ('avaliacoes', models.ManyToManyField(related_name='redacoesAvaliadas', through='RedifApp.Avaliacao', to='accounts.Usuario')),
                ('fk_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Redacao', to='accounts.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='redacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_avaliacao', to='RedifApp.redacao'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_avaliacao', to='accounts.usuario'),
        ),
    ]
