# Generated by Django 4.0.2 on 2022-07-06 20:50

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=300)),
                ('nota', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('titulacao', models.CharField(choices=[('1', 'Fundamental 2 ao 8°ano'), ('2', 'Cursando 9° ano'), ('3', 'Cursando Ensino Médio'), ('4', 'Ensino Médio Completo'), ('5', 'Ensino Médio Incompleto'), ('6', 'Cursando Ensino Superior'), ('7', 'Ensino Superior Completo')], max_length=1)),
                ('condicao', models.CharField(choices=[('A', 'Aluno'), ('P', 'Professor')], max_length=1)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Redacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('area', multiselectfield.db.fields.MultiSelectField(choices=[('CET', 'Ciencias Exatas e da Terra'), ('CB', 'Ciências Biológicas'), ('CSA', 'Ciências Sociais Aplicadas'), ('E', 'Engenharias'), ('LLA', 'Linguística, Letras e Artes'), ('CH', 'Ciências Humanas')], max_length=3)),
                ('tema', models.CharField(max_length=45)),
                ('data_criacao', models.DateTimeField(default=datetime.date.today)),
                ('conteudo', models.TextField(max_length=15000)),
                ('descricao', models.TextField(blank=True, default=None, max_length=300, null=True)),
                ('curtidas', models.SmallIntegerField(default=0)),
                ('compartilhamentos', models.SmallIntegerField(default=0)),
                ('avaliacoes', models.ManyToManyField(related_name='Avaliacoes', through='RedifApp.Avaliacoes', to='RedifApp.Usuario')),
                ('fk_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Redacao', to='RedifApp.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='avaliacoes',
            name='redacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Redacao_avaliacao', to='RedifApp.redacao'),
        ),
        migrations.AddField(
            model_name='avaliacoes',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario_avalicao', to='RedifApp.usuario'),
        ),
    ]
