# Generated by Django 4.0.3 on 2022-06-30 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RedifApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=45)),
                ('area', models.CharField(max_length=45)),
                ('dateCreation', models.DateTimeField()),
                ('content', models.TextField(max_length=700)),
                ('schooling', models.CharField(blank=True, choices=[('f', 'Fundamental'), ('em', 'Ensino médio'), ('g', 'Graduado'), ('pg', 'Pós-Graduado'), ('m', 'Mestre'), ('d', 'Doutor')], max_length=200, null=True)),
                ('fk_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
