# Generated by Django 4.0.3 on 2022-07-08 01:45

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RedifApp', '0002_alter_usuario_condicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=45, null=True)),
                ('area', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CET', 'Ciencias Exatas e da Terra'), ('CB', 'Ciências Biológicas'), ('CSA', 'Ciências Sociais Aplicadas'), ('E', 'Engenharias'), ('LLA', 'Linguística, Letras e Artes'), ('CH', 'Ciências Humanas')], default=['CET', 'CB', 'CSA', 'E', 'LLA', 'CH'], max_length=3, null=True)),
                ('tema', models.CharField(blank=True, default='All', max_length=45, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='condicao',
            field=models.CharField(choices=[('A', 'Aluno'), ('P', 'Professor')], max_length=1),
        ),
    ]
