# Generated by Django 4.0.3 on 2022-07-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedifApp', '0003_filtro_alter_usuario_condicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='condicao',
            field=models.CharField(choices=[('P', 'Professor'), ('A', 'Aluno')], max_length=1),
        ),
    ]
