# Generated by Django 4.0.3 on 2022-07-01 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RedifApp', '0003_redacao_comment_redacao_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redacao',
            name='schooling',
        ),
    ]
