# Generated by Django 4.0.3 on 2022-07-08 02:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RedifApp', '0004_alter_usuario_condicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtro',
            name='area',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CET', 'Ciencias Exatas e da Terra'), ('CB', 'Ciências Biológicas'), ('CSA', 'Ciências Sociais Aplicadas'), ('E', 'Engenharias'), ('LLA', 'Linguística, Letras e Artes'), ('CH', 'Ciências Humanas')], default=['CET', 'CB', 'CSA', 'E', 'LLA', 'CH'], max_length=40, null=True),
        ),
    ]
