# Generated by Django 4.0.3 on 2022-07-01 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedifApp', '0004_remove_redacao_schooling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redacao',
            name='dateCreation',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
