# Generated by Django 4.0.3 on 2022-07-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedifApp', '0005_alter_redacao_datecreation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redacao',
            old_name='content',
            new_name='conteudo',
        ),
        migrations.RenameField(
            model_name='redacao',
            old_name='dateCreation',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='redacao',
            old_name='topic',
            new_name='tema',
        ),
        migrations.RenameField(
            model_name='redacao',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='redacao',
            name='comment',
        ),
        migrations.AddField(
            model_name='redacao',
            name='comentario',
            field=models.CharField(blank=True, default=None, max_length=45, null=True),
        ),
    ]
