# Generated by Django 4.0.3 on 2022-07-08 04:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RedifApp', '0005_alter_filtro_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtro',
            name='area',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Ciencias Exatas e da Terra', 'Ciencias Exatas e da Terra'), ('Ciências Biológicas', 'Ciências Biológicas'), ('Ciências Sociais Aplicadas', 'Ciências Sociais Aplicadas'), ('Engenharias', 'Engenharias'), ('Linguística, Letras e Artes', 'Linguística, Letras e Artes'), ('Ciências Humanas', 'Ciências Humanas')], default=['CET', 'CB', 'CSA', 'E', 'LLA', 'CH'], max_length=40, null=True),
        ),
    ]
