# Generated by Django 4.0.3 on 2022-07-08 04:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RedifApp', '0006_alter_filtro_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtro',
            name='area',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CET', 'Ciencias Exatas e da Terra'), ('CB', 'Ciências Biológicas'), ('CSA', 'Ciências Sociais Aplicadas'), ('E', 'Engenharias'), ('LLA', 'Linguística, Letras e Artes'), ('CH', 'Ciências Humanas')], default=['CET', 'CB', 'CSA', 'E', 'LLA', 'CH'], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='condicao',
            field=models.CharField(choices=[('A', 'Aluno'), ('P', 'Professor')], max_length=1),
        ),
    ]
