# Generated by Django 4.0.3 on 2022-07-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedifApp', '0007_alter_redacao_conteudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redacao',
            name='conteudo',
            field=models.TextField(),
        ),
    ]
