# Generated by Django 4.0.3 on 2022-07-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedifApp', '0010_alter_redacao_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redacao',
            name='comentario',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='redacao',
            name='tema',
            field=models.CharField(default='topic', max_length=45),
        ),
    ]
